import Head from 'next/head';

import type { NextPage } from 'next';
import { Container } from 'react-bootstrap';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <link
          rel="stylesheet"
          href="https://rsms.me/linter/linter.css"
        />
      </Head>

      <main>
        <Container>
          <h1>About Page</h1>
        </Container>
      </main>
    </>
  );
};

export default About;
